### ISSUE TITLE
Force 4 spaces for constructor args and 2 for extends

### ISSUE THREAD

**Issue by ms-ati** [daniel-trinh/scalariform#103]
The option `doubleIndentClassDeclaration` doesn't do what I would expect, when it says that it meets the [scala styleguide description](http://docs.scala-lang.org/style/declarations.html)

> ...put each constructor argument on its own line, indented **four** spaces:

and

> ...then indent **four** spaces with each item being on its own line and **two** spaces for extensions; this provides visual separation between constructor arguments and extensions.:

In contrast, the current option appears to always indent the constructor arguments **two** spaces and then confusingly indents the extensions to **four** spaces, which seems to be the reverse of the style guide, and looks weird.

**Comment by sschaef** [comment]
This issue was moved to scala-ide/scalariform#160
