### ISSUE TITLE
Provide option to indent method parameters at level of method

### ISSUE THREAD

**Issue by nairbv** [daniel-trinh/scalariform#105]
When using the option -danglingCloseParenthesis=Preserve, the code:

    def foobar(a:Int,
               c:Int,
               b:String) = {
      "hi"
    }

Is reformatted to:

    def foobar(
      a: Int,
      c: Int,
      b: String) = {
      "hi"
    }

It would be nice if there were some way to preserve the method-level alignment.  If there's a new-line after the first open parenthesis, the code should be reformatted as in the example, but if not, I would think the parameters should be aligned to the indentation of the previous parameters (the level of the open-paren).

**Comment by sschaef** [comment]
This issue was moved to scala-ide/scalariform#158
