### ISSUE TITLE
move tickets and close all PRs

### ISSUE THREAD

**Issue by fommil** [daniel-trinh/scalariform#107]
It is finally alive again!

  https://github.com/scala-ide/scalariform/

Once everything is moved over, we can close the issue tracker and wiki here.

Your master branch should probably be updated to include a single README containing a note that upstream is the active repo again.

**Comment by fommil** [comment]
btw do you mind adding myself and @sschaef as contributors on this repo, so we have rights to close the tickets as we move them over, e.g. with https://github.com/google/github-issue-mover

**Comment by daniel-trinh** [comment]
@fommil @sschaef you guys should now have push access to this branch

**Comment by fommil** [comment]
cool, thanks! I think Simon has more time dedicated to this at the moment. I basically have about 10 seconds to myself each day before...

**Comment by sschaef** [comment]
PRs are all reviewed. Now I'm going to have a look at the issues.

**Comment by sschaef** [comment]
All issues are moved!

**Comment by fommil** [comment]
:fireworks:
