### ISSUE TITLE
Force annotations onto their own lines for block expressions and parameter clauses

### ISSUE THREAD

**Issue by daniel-trinh** [daniel-trinh/scalariform#12]
Annotations for expressions in blocks and parameter clauses currently are placed on the same line:

```scala
def asdf(
  @annotation one: Int,
  @a @b(c) two: String
)

class A extends B {
  @SomeImportantAnnotation(param = true) override val param: Int = 1

  @NotSoImportantAnnotation(param = false) val description: String = "Not so important"
}
```

Instead, it should be formatted as..

```scala
def asdf(
  @annotation 
  one: Int,
  @a 
  @b(c) 
  two: String
)

class A extends B {
  @SomeImportantAnnotation(param = true) 
  override val param: Int = 1

  @NotSoImportantAnnotation(param = false) 
  val description: String = "Not so important"
}

```

This would most likely only affect parameters that are already placed on their own line, so
something like this wouldn't be affected:

```scala
def asdf(@annotation one: Int, @a @b(c) two: String)
```

stays as..

```scala
def asdf(@annotation one: Int, @a @b(c) two: String)
```

Implementation details note: this needs to be implemented without breaking the `AlignParameters` feature

See here for similar issue on original branch: https://github.com/mdr/scalariform/issues/91

**Comment by patrikvarga** [comment]
+1, this is very annoying, especially that it is not conforming the Scala Style Guide and thus makes the following statement in the documentation invalid:
"Scalariform is compatible with the Scala Style Guide in the sense that, given the right preference settings, source code that is initially compiliant with the Style Guide will not become uncompliant after formatting."

**Comment by sschaef** [comment]
This issue was moved to scala-ide/scalariform#185
