### ISSUE TITLE
AlignParameters: Missing space between colon and type when special characters are used 

### ISSUE THREAD

**Issue by daniel-trinh** [daniel-trinh/scalariform#21]
When alignParameters is enabled, the colon between the name and type sometimes does not preserve the extra space after the type.

Failing test case:
```scala
  """def a(
    |  underscore_ : Int = 1,
    |  underscore2__ : String = "1"
    |)""" ==>
  """def a(
    |  underscore_ :   Int    = 1,
    |  underscore2__ : String = "1"
    |)"""
```

Currently, the above example gets reformatted as this:
```scala
def a(
  underscore_ :  Int    = 1,
  underscore2__ :String = "1"
)
```
Note the lack of space between the type and colon.

**Comment by sschaef** [comment]
This issue was moved to scala-ide/scalariform#182
