### ISSUE TITLE
ask for ownership and publish under org.scalariform

### ISSUE THREAD

**Issue by fommil** [daniel-trinh/scalariform#28]
it would be great if you could move your repo to a "scalariform-bak" and get the original author to hand ownership to you, as this appears to be the only maintained branch. At the same time, asking him to give you permissions to publish to org.scalariform would be wonderful (that would make it easier to get the sbt-plugin to use your branch).

Or, maybe the right thing is to create a scalariform organisation and get the original author to move the repo to there, adding you as dev/admin/whatever.

Scalariform is too important to rot.

**Comment by daniel-trinh** [comment]
Ownership of the project has not been transferred in the original fork, but at least I have publish rights to `org.scalariform` now.

**Comment by fommil** [comment]
w00t!

**Comment by ktoso** [comment]
Excellent, looking forward to scalariforms maintainance-revival under that group name :-)
