### ISSUE TITLE
implicit argument lists

### ISSUE THREAD

**Issue by fommil** [daniel-trinh/scalariform#36]
It is fairly standard practice in implicit-heavy libraries to write implicit parameter lists like this

```scala
  def canBuildFromFormat[F, E, T]()(implicit
    cbf: CanBuildFrom[F, E, T],
    ef: SexpFormat[E]
  )
```

but unfortunately I can't set up scalariform to use this trailing-implicit format. Is this something you could support with a new option?

Note that it is possible to do this sort of thing

```scala
  def canBuildFromFormat[F, E, T]()(
    implicit
    cbf: CanBuildFrom[F, E, T],
    ef: SexpFormat[E]
  )
```

**Comment by nairbv** [comment]
I'm looking for any way to use scalariform without condensing curried function signatures, but the issue isn't just with implicit parameters, it's any kind of currying.
e.g., when I see code like:

    def aReallyLongMethodName(thatHasSomeParameters:WithLongTypes)(andThenAnother:ParameterList) = foo

I'd like to be able to write it as:

    def aReallyLongMethodName(thatHasSomeParameters:WithLongTypes)
                             (andThenAnother:ParameterList) = foo

But it automatically gets reformatted back to the first one by scalariform.  This prevents me from keeping a tight limit on org.scalastyle.file.FileLineLengthChecker in scalaStyle, and I've often seen single lines of code that get excessively long.

From the preview here it looks like characters aren't monospaced, but what I was getting at in my example is I would typically align the open-paren of my curried parameters, implicit or not.

Ideally I think I'd rather just have scalariform not touch any whitespace between a close and then open paren.  I hadn't considered your style for writing implicit parameters.

**Comment by nairbv** [comment]
I think I'll create a separate issue for what I'm describing since the option I'm requesting for curried parameters is a bit different.

**Comment by sschaef** [comment]
This issue was moved to scala-ide/scalariform#180
