### ISSUE TITLE
The parser doesn't accept DOT inside type parameters at patterns

### ISSUE THREAD

**Issue by guersam** [daniel-trinh/scalariform#44]
The parser fails at this case with the error `Expected token RBRACKET but got Token(DOT,.,89,.)`:

```scala
object FailingCase {
  def failingMethod(v: Any) =
    v match {
      case v: List[scala.Int] => v
    }
}
```

Changing `scala.Int` to `Int` makes it work.

**Comment by ceedubs** [comment]
This is also an issue when you are accessing a type member of an object. I encountered it [here](https://github.com/ceedubs/cats/commit/0e4e235758645c432c5652f2653d0723c21e0773).
