### ISSUE TITLE
Figure out how to publish scalariform-cli jar to maven

### ISSUE THREAD

**Issue by daniel-trinh** [daniel-trinh/scalariform#49]

**Comment by bambuchaAdm** [comment]
Current build tool is maven or sbt ?

**Comment by ktoso** [comment]
he most likely means "to maven (central)" :wink:

**Comment by bambuchaAdm** [comment]
Ok, but it could be done in both: maven and sbt. But it's just waste of time and energy for duplication this :wink:

**Comment by mlbileschi** [comment]
maven central was what prompted this issue to be opened

**Comment by mlbileschi** [comment]
@daniel-trinh it seems like you can now do this: is there anything that remains unknown? (I saw that you have permissions now)

**Comment by daniel-trinh** [comment]
The blocker wasn't actually getting maven-central access to `org.scalariform`, I could have pushed to `com.danieltrinh` -- the unknown right now is figuring out how to add the cli jar so that it shows up when publishing in general (it just so happens it needs to end up in maven-central)

**Comment by mlbileschi** [comment]
I think this does it, though I can't test
https://gist.github.com/mlbileschi/081b93042eb4b3ab1b1b

**Comment by mlbileschi** [comment]
Thank you very, very much for doing this.

**Comment by daniel-trinh** [comment]
Here's the jar in maven central:
http://repo1.maven.org/maven2/org/scalariform/cli_2.10/0.1.6/cli_2.10-0.1.6-assembly.jar
