### ISSUE TITLE
Prepare for 0.1.6 release

### ISSUE THREAD

**Issue by daniel-trinh** [daniel-trinh/scalariform#52]
+ Undo #40 
+ Switch publish namespace from `com.danieltrinh` to `org.scalariform`
+ Create dummy project that points the `com.danieltrinh` stuff to `org.scalariform`, so users don't have to switch namespaces in their code (although they will still have to switch versions)
+ Update release notes, scala versions

**Comment by fommil** [comment]
:smile:

**Comment by daniel-trinh** [comment]
@fommil How important is it to actually create a dummy project with the `com.danieltrinh` namespace to `org.scalariform`? I spent a few minutes trying to figure out how to set this up via the sbt build and haven't figured out how to do it yet.

**Comment by fommil** [comment]
Pretty important. Should be simple, it's just an empty project wind one dependency. To avoid creating a multi module project, just do it on a fresh branch.

**Comment by daniel-trinh** [comment]
This has been published and should be out in maven central now for `2.11`, `2.10`, `2.9.3`, and `2.9.2`, under both `org.scalariform` and `com.danieltrinh`. 

I didn't actually go with the dummy project route, and instead published the same project twice under both namespaces, but I imagine the effect should be the same.

**Comment by fommil** [comment]
AWESOME! :grinning:
