### ISSUE TITLE
Investigate supporting scalariform in homebrew

### ISSUE THREAD

**Issue by daniel-trinh** [daniel-trinh/scalariform#53]
It would be neat to be able to `brew install scalariform` to use the standalone cli jar on OSX.

Things to do:
+ Finish #52 so the CLI jar is up in maven central
+ Create a homebrew formula that points to the cli jar

**Comment by jawshooah** [comment]
Is the cli jar already published somewhere and ready to download? If so, I could whip up a Homebrew formula right now.

**Comment by daniel-trinh** [comment]
Not yet -- it will be up in maven central once #52 is done, and I might also upload it via github releases afterwards.

**Comment by daniel-trinh** [comment]
0.1.6 has been published. Links to download:

http://repo1.maven.org/maven2/org/scalariform/cli_2.11/0.1.6/cli_2.11-0.1.6-assembly.jar
https://github.com/daniel-trinh/scalariform/releases/tag/0.1.6

**Comment by jawshooah** [comment]
Formula submitted at Homebrew/homebrew#38688

**Comment by daniel-trinh** [comment]
w00t!
```
brew install scalariform
==> Downloading https://github.com/daniel-trinh/scalariform/releases/download/0.1.6/
######################################################################## 100.0%
```
