### ISSUE TITLE
CLI tool returns non-zero exit code when input is correctly formatted

### ISSUE THREAD

**Issue by jawshooah** [daniel-trinh/scalariform#61]
From `scalariform --help`:

> --test, -t Check the input(s) to see if they are correctly formatted, return a non-zero error code if not.

However, it seems to be doing the opposite:

```
$ scalariform --test Formatted.scala
[OK]     Formatted.scala

$ echo $?
1

$ scalariform --test Unformatted.scala
[FAILED] Unformatted.scala

$ echo $?
0
```

**Comment by daniel-trinh** [comment]
#74 should fix this

**Comment by jawshooah** [comment]
Seems you're right. Thanks!
