### ISSUE TITLE
Allow sorting of imports

### ISSUE THREAD

**Issue by prettynatty** [daniel-trinh/scalariform#66]
It would be great to be able to sort imports using scalariform.
Without automatic imports sorting teams are suffering from merge conflicts and unorganized imports mess.

There is the same issue in old project: mdr/scalariform#67.

**Comment by magnusart** [comment]
+1 I really miss this. 
In addition warnings could be produced for unused import, that would be super helpful.

**Comment by johnhanks1** [comment]
+1 This would be great!

**Comment by ngbinh** [comment]
+1

**Comment by cristipp** [comment]
+1

**Comment by sschaef** [comment]
This issue was moved to scala-ide/scalariform#175
