### ISSUE TITLE
Publish Scalariform website here

### ISSUE THREAD

**Issue by non** [daniel-trinh/scalariform#67]
The website link for this project is still [http://mdr.github.io/scalariform/](http://mdr.github.io/scalariform).

In the long run this won't work if you need to update the documentation. But it also is confusing for the abandoned repo to still host the current website (which is linked to by many other sites).

Ideally the site could be published to [http://daniel-trinh.github.io/scalariform](http://mdr.github.io/scalariform).

**Comment by bkern** [comment]
+1 this would be helpful I have had a longer path here to find this was latest maintained version of this tool

**Comment by sschaef** [comment]
this ticket is no longer needed since scala-ide owns scalariform
