### ISSUE TITLE
Format for comprehensions

### ISSUE THREAD

**Issue by justjoheinz** [daniel-trinh/scalariform#72]
In analogy to formatting match { case => ... } statements it would be awesome if there would be support for for comprehensions, e.g.

```scala
for {
  a <- something
  anotherValue <- foo
} yield {
  ...
}
```

becomes

```scala
for {
  a            <- something
  anotherValue <- foo
} yield {
 ...
}
```

**Comment by Fristi** [comment]
:+1:

**Comment by sschaef** [comment]
This issue was moved to scala-ide/scalariform#171
