### ISSUE TITLE
options to align case statements and variable definitions

### ISSUE THREAD

**Issue by fommil** [daniel-trinh/scalariform#76]
currently scalariform only supports aligning single line case statements, eg.

```scala
case foo: Foo => ...
case bar         => ...
```

but it would be good if there was an option for multi line cases and also if there was a similar thing for variable definitions. At the very least, an option not to reformat the location of the `=` for variable definitions would be good.

**Comment by sschaef** [comment]
This issue was moved to scala-ide/scalariform#170
