### ISSUE TITLE
Backwards compatible dangling parenthesis

### ISSUE THREAD

**Issue by fommil** [daniel-trinh/scalariform#79]
I'm sure I had a ticket for this. But it seems to have disappeared. Maybe I dreamt it.

One of the biggest changes introduced by this fork was better dangling parenthesis behaviour. However, there is no option to get the old behaviour and this is stopping people from being able to upgrade scalariform, or in some extreme cases (like at my work) Eclipse.

Can you please look into this or let us know how to add the option. This is becoming really quite critical for me.

**Comment by kpmeen** [comment]
+1

**Comment by andrebeat** [comment]
I think [this](https://github.com/daniel-trinh/scalariform/issues/29) is the issue you're looking for. I also hope that you meant to say Ensime and not Eclipse :-P 

+1 from me too.

**Comment by fommil** [comment]
@andrebeat well, Eclipse users can upgrade to ENSIME ;-) But actually I did mean Eclipse... some teams can't upgrade because their formatting all changes and that totally breaks merging and branching strategies. This is actually a really big deal.

**Comment by fommil** [comment]
I'm going to look into this today / tomorrow. @daniel-trinh I'll send you a PR and try to help round the troops of scala-ide to try and make the documentation around scalariform a bit better for people to know where active development is happening.

**Comment by jawshooah** [comment]
Note that #80 would address this (and by extension, #29).

**Comment by fommil** [comment]
@jawshooah awesome! I'll take a look at that

**Comment by fommil** [comment]
actually, I think you found the ticket that I thought I'd dreamt up. Dupe of #29
