### ISSUE TITLE
failed to parse type signature

### ISSUE THREAD

**Issue by fommil** [daniel-trinh/scalariform#81]
Since upgrading recently, I've been seeing errors to parse this trivial file:

```scala
package org.ensime.indexer

import org.apache.lucene.document._

package object lucene {
  implicit class RichEntity[T <: Entity](e: T) {
    def toDocument(implicit p: DocumentProvider[T]) = p.toDocument(e)
  }

  implicit class RichDocument(d: Document) {
    def toEntity[T](implicit p: DocumentRecovery[T]) = p.toEntity(d)
  }
}
```

with the error

```
[warn] Scalariform parser error for /path/to/file.scala: Expected token RBRACKET but got Token(XML_START_OPEN,<,865,<)
```

the offset matches 865 is `[T <: Entity]` on the file on disk (I've removed a bunch of irrelevant scaladocs here).

**Comment by daniel-trinh** [comment]
This should have been fixed with https://github.com/daniel-trinh/scalariform/pull/73 (0.1.7), which version are you currently using?

**Comment by fommil** [comment]
0.1.7

**Comment by fommil** [comment]
actually, that might not be true. In my project definition I am using `sbt-scalariform` 1.4.0 so whatever it uses. We use 0.1.7 in ensime-server as a dependency.

**Comment by daniel-trinh** [comment]
sbt-scalariform is up to 1.5.1 now, 1.4.0 is using scalariform 0.1.6

**Comment by fommil** [comment]
ok, I'll change and check that, thanks! Closing for now, will reopen if I see anything else. If you could have a look at that other PR and merge that would be really fantastic.

**Comment by fommil** [comment]
thanks, that fixes it!

**Comment by fommil** [comment]
@daniel-trinh please look at https://github.com/daniel-trinh/scalariform/pull/80 and merge/release if you are comfortable.
