### ISSUE TITLE
Do any rules organize dead imports

### ISSUE THREAD

**Issue by bkern** [daniel-trinh/scalariform#86]
Re reading the docs it does not seem apparent to me any rule touches this area however locally when I ran v1.4 via scalariformFormat and examined changes I see imports cleaned up which is great but I cannot understand which rule was responsible. Since I am running 1.4 I included scalariformSettings in my build.sbt ... I dug into that setting as well but couldn't find an answer

**Comment by bkern** [comment]
confirmed same result with 1.51.

**Comment by daniel-trinh** [comment]
No, there's nothing that removes unused / dead imports. It's not scalariform that is doing this, scalariform has no intelligent semantic knowledge of the source code it scans.
