### ISSUE TITLE
What am I missing?  AlignParameters not working for me

### ISSUE THREAD

**Issue by gzoller** [daniel-trinh/scalariform#94]
In my Build.scala I have something like this:
```scala
lazy val basicSettings = scalariformSettings ++ Seq(
		ScalariformKeys.preferences := ScalariformKeys.preferences.value
			.setPreference(AlignArguments,true)
			.setPreference(DoubleIndentClassDeclaration,true)
			.setPreference(AlignParameters,true),
// more settings here
```

I mix in my settings into my project and format.  My classes look like this:

```scala
case class Harness(
    name: String,
    version: Int, // sequential version of the Harness format structure
    description: String,
    env: String,
    isProd: Boolean,
    facilities: Facilities,
    isContainer: Boolean, // Set to World server's Docker container
    applications: List[AppConfig]) {
  def appConfig[T](appName: String) = applications.find(_.name == appName).map(_.asInstanceOf[T])
}
```

I don't see any alignment of the parameters (tried AlignArguments too).  I can toggle true/false on the DoubleIndentClassDeclaration parameter to confirm that indeed the settings are being picked up.

Any idea what I'm doing wrong?
Thanks,
Greg

**Comment by daniel-trinh** [comment]
What version of scalariform are you using? Is this being used through sbt-scalariform?

**Comment by gzoller** [comment]
Yes, I'm using sbt-scalariform, and I've just seen the note in this repo to use your version of sbt-scalariform.  Tried that and worked great!
