### ISSUE TITLE
BUG: not possible to set `defaultScalariformSettings` in default settings

### ISSUE THREAD

**Issue by fommil** [daniel-trinh/scalariform#95]
`override val settings = super.settings ++ defaultScalariformSettings`

in a `.scala` style project will result in missing tasks. It would be useful if this was allowed.

**Comment by daniel-trinh** [comment]
Is this with sbt-scalariform?

**Comment by fommil** [comment]
yup, I think its a `Configuration` scope thing. Not a big deal because it can be worked around by adding the settings to each `Project`.

**Comment by sschaef** [comment]
This issue was moved to scala-ide/scalariform#162
